import Link from 'next/link'

const agents = {
  'inbox-agent': { kicker:'COMMUNICATION AGENT', title:'Inbox Agent', lead:'Vom Posteingang zum erledigten Vorgang.', intro:'Der Inbox Agent liest eingehende Nachrichten, erkennt Anliegen und Dringlichkeit, zieht relevante Informationen aus verbundenen Systemen heran und bereitet den nächsten Schritt vor.', tasks:['E-Mails nach Anliegen, Kunde und Priorität klassifizieren','Informationen und Anhänge strukturiert extrahieren','Antwortentwürfe auf Basis freigegebener Wissensquellen erstellen','Tickets, Aufgaben oder CRM-Vorgänge automatisch anlegen','Unsichere oder sensible Fälle gezielt an Menschen eskalieren'], example:'Eine Kundenanfrage trifft ein. Der Agent erkennt Produkt und Anliegen, sucht die passende Dokumentation, prüft vorhandene Kundendaten und erstellt einen Antwortentwurf. Erst nach definierten Regeln wird automatisch versendet oder an eine Fachperson übergeben.', systems:'Microsoft 365 / Gmail · CRM · Helpdesk · ERP · Wissensdatenbanken', benefit:'Weniger Sortier- und Recherchearbeit, schnellere Reaktionszeiten und ein konsistenter Prozess.' },
  'document-agent': { kicker:'KNOWLEDGE AGENT', title:'Document Agent', lead:'Unternehmenswissen, das tatsächlich gefunden wird.', intro:'Der Document Agent erschliesst freigegebene Dokumente und macht Wissen über natürliche Sprache nutzbar. Antworten können mit Fundstellen und Quellen versehen werden.', tasks:['Handbücher, Richtlinien, Verträge und technische Dokumente erschliessen','Fragen über mehrere Dokumentbestände hinweg beantworten','Quellen und Fundstellen nachvollziehbar ausgeben','Metadaten und Inhalte aus Dokumenten extrahieren','Zugriff auf Wissen nach Rollen und Berechtigungen steuern'], example:'Ein Servicetechniker fragt nach einer bestimmten Montagevorgabe. Statt mehrere PDFs zu durchsuchen, erhält er eine kompakte Antwort mit Verweis auf die freigegebene Originalquelle.', systems:'SharePoint · Fileserver · DMS · PDF/Office · Wikis · Datenbanken', benefit:'Weniger Suchzeit, schnellere Einarbeitung und besser nutzbares Unternehmenswissen.' },
  'process-agent': { kicker:'OPERATIONS AGENT', title:'Process Agent', lead:'Routinearbeit wird zu einem kontrollierten Workflow.', intro:'Der Process Agent verbindet Systeme, Entscheidungen und Arbeitsschritte. Er kann Daten prüfen, Informationen übertragen, Folgeaktionen auslösen und bei Ausnahmen einen Menschen einbeziehen.', tasks:['Daten zwischen Anwendungen übertragen und validieren','Wiederkehrende Prüf- und Freigabeschritte orchestrieren','Dokumente oder Datensätze vorbereiten','Statusänderungen und Folgeaufgaben auslösen','Ausnahmen protokollieren und eskalieren'], example:'Eine Bestellung wird erkannt, Daten werden geprüft und mit Stammdaten abgeglichen. Der Agent bereitet den Vorgang im Zielsystem vor und legt Sonderfälle zur manuellen Prüfung vor.', systems:'ERP · CRM · APIs · Datenbanken · Microsoft 365 · Fachanwendungen', benefit:'Weniger Copy-Paste, weniger Medienbrüche und nachvollziehbare Abläufe.' },
  'service-agent': { kicker:'SERVICE AGENT', title:'Service Agent', lead:'Support, der Wissen und Prozesse verbindet.', intro:'Der Service Agent unterstützt Mitarbeitende oder Kunden bei wiederkehrenden Servicefällen und verbindet Dialog, Wissenssuche und definierte Aktionen.', tasks:['Anfragen klassifizieren und zusammenfassen','Passende Lösungen aus freigegebenem Wissen finden','Rückfragen gezielt stellen','Tickets anlegen, ergänzen oder weiterleiten','Komplexe Fälle an die richtige Fachperson eskalieren'], example:'Ein Kunde beschreibt einen Fehler. Der Agent sammelt fehlende Angaben, gleicht Symptome mit der Wissensbasis ab und schlägt einen nächsten Schritt vor. Kritische Fälle gehen direkt an den Support.', systems:'Helpdesk · CRM · Knowledge Base · E-Mail · Webchat · Produktdaten', benefit:'Kürzere Bearbeitungszeiten und mehr Fokus des Teams auf anspruchsvolle Fälle.' },
  'knowledge-copilot': { kicker:'INTERNAL AI', title:'Knowledge Copilot', lead:'Ein sicherer KI-Zugang zum internen Know-how.', intro:'Der Knowledge Copilot ist ein rollenbasierter Assistent für Mitarbeitende. Er kann internes Wissen zusammenführen, Inhalte erklären, Entwürfe erstellen und bei täglichen Wissensaufgaben unterstützen.', tasks:['Interne Fragen aus freigegebenen Quellen beantworten','Inhalte zusammenfassen und vergleichen','Entwürfe, Checklisten und Arbeitsgrundlagen vorbereiten','Neue Mitarbeitende beim Onboarding unterstützen','Abteilungs- oder rollenspezifische Wissensräume bereitstellen'], example:'Eine neue Mitarbeiterin fragt nach dem internen Ablauf für einen bestimmten Vorgang. Der Copilot erklärt die Schritte und verweist auf die aktuell gültigen Dokumente.', systems:'SharePoint · Intranet · DMS · Wiki · Teams · Datenbanken', benefit:'Wissen wird schneller zugänglich und bleibt näher an den freigegebenen Unternehmensquellen.' },
  'local-ai-stack': { kicker:'PRIVATE AI', title:'Local AI Stack', lead:'KI dort betreiben, wo Ihre Anforderungen es verlangen.', intro:'Nicht jeder Anwendungsfall gehört in eine öffentliche Cloud. CARL.AI konzipiert je nach Schutzbedarf Cloud-, Private-Cloud-, Hybrid- oder lokale Architekturen.', tasks:['Geeignete Modelle und Infrastruktur auswählen','Lokale oder private Inferenz bereitstellen','RAG und interne Wissensquellen anbinden','Berechtigungen, Logging und Guardrails konzipieren','Cloud- und lokale Modelle gezielt kombinieren'], example:'Sensible Dokumente bleiben in der eigenen Infrastruktur. Ein lokal betriebenes Modell verarbeitet die Inhalte, während weniger sensible Aufgaben optional über spezialisierte Cloud-Modelle laufen können.', systems:'On-Prem Server · Private Cloud · Vector DB · APIs · Identity & Access', benefit:'Mehr Kontrolle über Datenflüsse, Modellwahl und Betriebsarchitektur.' }
}

export function generateStaticParams(){ return Object.keys(agents).map(slug=>({slug})) }

export default function AgentPage({params}){
  const a=agents[params.slug] || agents['process-agent']
  return <main className="subpage"><header className="subnav container"><Link href="/" className="mini-brand">◌ CARL<span>.AI</span></Link><nav><Link href="/#agents">Agents</Link><Link href="/ki-modelle">KI-Modelle</Link><Link href="/#private">Private AI</Link></nav><Link className="nav-cta" href="/#contact">Projekt besprechen →</Link></header>
    <section className="container detail-hero"><div className="eyebrow"><i/> {a.kicker}</div><h1>{a.title}</h1><h2>{a.lead}</h2><p>{a.intro}</p><div className="hero-actions"><Link className="button primary" href="/#contact">Use Case besprechen →</Link><Link className="button ghost" href="/#agents">Alle Agents</Link></div></section>
    <section className="container detail-grid"><article className="info-panel"><small>WAS DER AGENT ÜBERNEHMEN KANN</small><h2>Konkrete Aufgaben</h2><ul>{a.tasks.map(x=><li key={x}>✓ <span>{x}</span></li>)}</ul></article><article className="example-panel"><small>BEISPIEL-WORKFLOW</small><h2>So kann es im Alltag aussehen.</h2><p>{a.example}</p><div className="flowline"><span>INPUT</span><b>→</b><span>CARL.AI</span><b>→</b><span>AKTION</span><b>→</b><span>KONTROLLE</span></div></article></section>
    <section className="container two-panels"><article><small>TYPISCHE ANBINDUNGEN</small><h3>{a.systems}</h3></article><article><small>POTENZIELLER NUTZEN</small><h3>{a.benefit}</h3></article></section>
    <section className="container detail-cta"><h2>Passt dieser Agent zu Ihrem Prozess?</h2><p>Wir prüfen zuerst Prozess, Daten, Risiken und Wirtschaftlichkeit – und entscheiden danach, welche Architektur wirklich sinnvoll ist.</p><Link className="button white" href="/#contact">Potenzialgespräch starten →</Link></section>
  </main>
}
