import Link from 'next/link'

const models=[
 {name:'OpenAI',tag:'CLOUD / ENTERPRISE',title:'Stark für Reasoning, Sprache und multimodale Workflows',text:'Geeignet für anspruchsvolle Agenten, Dokumentanalyse, strukturierte Extraktion, Textarbeit und Workflows mit Tool-Nutzung. Für Geschäftsanwendungen betrachten wir API- und Enterprise-Datenschutzoptionen getrennt von Consumer-Angeboten.',uses:['Agenten mit komplexen Entscheidungen','Dokument- und Datenanalyse','Text, Strukturierung und Assistenz','Multimodale Anwendungsfälle']},
 {name:'Claude',tag:'CLOUD / ENTERPRISE',title:'Besonders interessant für umfangreiche Wissens- und Textarbeit',text:'Claude kann je nach Projekt für lange Dokumentkontexte, Wissensarbeit, Analyse, Agenten-Workflows und hochwertige Textverarbeitung eingesetzt werden. Welche Variante passt, hängt von Daten, Integrationen und Governance ab.',uses:['Dokument- und Wissensarbeit','Analyse umfangreicher Inhalte','Interne Assistenzsysteme','Agentische Workflows']},
 {name:'Gemini',tag:'GOOGLE ECOSYSTEM',title:'Interessant, wenn Prozesse stark im Google-Ökosystem liegen',text:'Gemini kann besonders dort sinnvoll sein, wo Google Workspace und Google Cloud bereits zentrale Bestandteile der IT-Landschaft sind. Enterprise-Schutzmechanismen und vorhandene Workspace-Kontrollen können dabei relevant sein.',uses:['Google-Workspace-nahe Prozesse','Multimodale Analyse','Unternehmenssuche und Assistenz','Cloud-native Integrationen']},
 {name:'Mistral',tag:'EU / SELF-HOSTING',title:'Flexible Option für private und selbst betriebene KI',text:'Mistral bietet Modelle und Deployment-Optionen, die je nach Modell lokal beziehungsweise auf eigener Infrastruktur betrieben werden können. Das macht die Plattform für kontrollierte Private-AI-Architekturen besonders interessant.',uses:['On-Premise und Private Cloud','RAG über interne Dokumente','Kontrollierte Agenten-Workflows','Europäische KI-Architekturen']},
 {name:'Open Models',tag:'LOCAL / ON-PREMISE',title:'Lokale Modelle für maximale Infrastrukturkontrolle',text:'Je nach Use Case können geeignete Open-Weight-Modelle vollständig auf eigener Hardware oder in einer privaten Umgebung laufen. CARL.AI wählt nicht nach Markenname, sondern nach Qualität, Hardwarebedarf, Lizenz, Datenschutz und Aufgabe.',uses:['Sensible interne Daten','Offline- oder abgeschottete Systeme','Spezialisierte Modelle','Kostenkontrolle bei hoher Nutzung']}
]

export default function Models(){return <main className="subpage"><header className="subnav container"><Link href="/" className="mini-brand">◌ CARL<span>.AI</span></Link><nav><Link href="/#agents">Agents</Link><Link href="/ki-modelle">KI-Modelle</Link><Link href="/#private">Private AI</Link></nav><Link className="nav-cta" href="/#contact">Projekt besprechen →</Link></header>
<section className="container models-hero"><div className="eyebrow"><i/> MODEL STRATEGY</div><h1>Nicht jede KI passt<br/><span>zu jeder Aufgabe.</span></h1><p>CARL.AI ist modelloffen. Wir kombinieren Cloud-, Enterprise- und lokale Modelle so, dass Qualität, Datenschutz, Kosten und Integrationsfähigkeit zum konkreten Geschäftsprozess passen.</p></section>
<section className="container model-principle"><div><small>UNSER PRINZIP</small><h2>Der Use Case entscheidet.<br/>Nicht das Logo auf dem Modell.</h2></div><p>Ein Agent kann sogar mehrere Modelle verwenden: ein schnelles Modell für Klassifikation, ein stärkeres Modell für komplexe Analyse und ein lokales Modell für besonders sensible Inhalte. So entsteht eine Architektur statt einer Abhängigkeit von einem einzelnen Anbieter.</p></section>
<section className="container model-list">{models.map((m,i)=><article className="model-row" key={m.name}><div className="model-index">0{i+1}</div><div><small>{m.tag}</small><h2>{m.name}</h2><h3>{m.title}</h3><p>{m.text}</p></div><div className="model-uses"><small>BEISPIEL-EINSATZ</small>{m.uses.map(x=><span key={x}>↗ {x}</span>)}</div></article>)}</section>
<section className="container architecture"><div className="eyebrow"><i/> HYBRID INTELLIGENCE</div><h2>Ein Prozess. <span>Mehrere Intelligenzen.</span></h2><div className="arch-flow"><div><b>01</b><strong>INPUT</strong><small>E-Mail · Dokument · ERP</small></div><i>→</i><div><b>02</b><strong>ROUTER</strong><small>Aufgabe & Schutzbedarf</small></div><i>→</i><div className="arch-core"><b>03</b><strong>BEST FIT AI</strong><small>Cloud · Private · Local</small></div><i>→</i><div><b>04</b><strong>ACTION</strong><small>Antwort · System · Mensch</small></div></div></section>
<section className="container security-note"><h2>Datenschutz beginnt vor der Modellauswahl.</h2><p>Wir betrachten Datenklassen, Aufbewahrung, Berechtigungen, Protokollierung, menschliche Freigaben und den Ort der Verarbeitung bereits im Lösungsdesign. „Lokal“ ist dabei eine mögliche Architektur – nicht automatisch für jeden Prozess die beste.</p><Link href="/#contact" className="button primary">Architektur besprechen →</Link></section>
</main>}
